In [1]:
import numpy as np
np.__version__

'1.25.2'

In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
l = [1,2,4,5,6,7,8,9]
arr = np.array(l)
print(arr)
print(type(arr))

[1 2 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [10]:
a = {11,22,33,44,55,66}
arr = np.array(a)
print(arr)
print(type(arr))

{33, 66, 22, 55, 11, 44}
<class 'numpy.ndarray'>


In [12]:
b = np.array([10,20,30,40,50,60])
print(b)
print(type(b))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [13]:
tup = (1,2,3,4,5,6,7)
arr = np.array(tup)
print(arr)
print(type(arr))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [17]:
array = np.array([1,2,3,4,5,6])
print(array)
print(type(array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [16]:
a = ([1,2,3,4,5,6,7,8,9])
b = np.array(a)
print(b)

[1 2 3 4 5 6 7 8 9]


In [18]:
arr = np.array([1,2,3,4,5,6,7,])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7]
1


In [19]:
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)

[10 20 30 40 50]
1


In [20]:
tup = (1,2,3,4,5,6,7,8)
arr = np.array(tup)
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8]
1


In [21]:
l = [11,22,33,44,55,66]
arr = np.array(l)
print(arr)
print(arr.ndim)


[11 22 33 44 55 66]
1


In [22]:
s = {100,200,300,400,500}
arr = np.array(s)
print(arr)
print(arr.ndim)

{400, 100, 500, 200, 300}
0


In [23]:
# 0 - d array
arr = np.array(110)
print(arr)
print(arr.ndim)

110
0


In [24]:
arr = np.array(100)
print(arr)
print(arr.ndim)

100
0


In [26]:
l = (10)
arr = np.array(l)
print(arr)
print(arr.ndim)

10
0


In [27]:
s = {100}
arr = np.array(s)
print(arr)
print(arr.ndim)

{100}
0


In [28]:
tup = (0)
arr = np.array(tup)
print(arr)
print(arr.ndim)

0
0


In [29]:
# 1- d array
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [30]:
tup = (10,20,30,40)
arr = np.array(tup)
print(arr)
print(arr.ndim)

[10 20 30 40]
1


In [31]:
l = [100]
arr = np.array(l)
print(arr)
print(arr.ndim)

[100]
1


In [33]:
ar = ([10,20,30,40,50,60])
arr = np.array(ar)
print(arr)
print(arr.ndim)

[10 20 30 40 50 60]
1


In [35]:
s = [1,2,3,4,5,6]
arr = np.array(s)
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [36]:
# 2 - d array
ar = ([[10,20,30],[40,50,60]])
arr = np.array(ar)
print(arr)
print(arr.ndim)

[[10 20 30]
 [40 50 60]]
2


In [38]:
l = [[1,2,3,4,5,6]]
ar = np.array(l)
print(ar)
print(ar.ndim)

[[1 2 3 4 5 6]]
2


In [39]:
s = ([[11,22,33,44,55]])
ar = np.array(s)
print(ar)
print(ar.ndim)

[[11 22 33 44 55]]
2


In [40]:
a = [[100]]
ar = np.array(a)
print(ar)
print(ar.ndim)

[[100]]
2


In [42]:
array = [[1,2,3,4]]
ar = np.array(array)
print(ar)
print(ar.ndim)

[[1 2 3 4]]
2


In [43]:
# 3 - d array
ar = [[[1,2,3,4,5]]]
arr = np.array(ar)
print(arr)
print(arr.ndim)

[[[1 2 3 4 5]]]
3


In [44]:
l = [[[10,20,30,40,50]]]
arr = np.array(l)
print(arr)
print(arr.ndim)

[[[10 20 30 40 50]]]
3


In [45]:
tup = ([[[11,22,33],[44,55,66]]])
ar = np.array(tup)
print(ar)
print(ar.ndim)

[[[11 22 33]
  [44 55 66]]]
3


In [46]:
s = [[[1000]]]
ar = np.array(s)
print(ar)
print(ar.ndim)

[[[1000]]]
3


In [47]:
a = [[[10,20],[30,40]]]
ar = np.array(a)
print(ar)
print(ar.ndim)

[[[10 20]
  [30 40]]]
3


In [62]:
# access array 1- d array
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr[3])
print(arr[-1])
print(arr[0,])
print('\n')
l = [10,20,30,40,50]
arr = np.array(l)
print(arr)
print(arr[4])
print(arr[0])
print('\n')
tup = (11,22,33,44,55)
arr = np.array(tup)
print(arr)
print(arr[2])
print(arr[-1])
print('\n')
a = [10,20]
arr = np.array(a)
print(arr)
print(arr[-1])
print('\n')
b = ([1,2,3,4,5])
ar = np.array(b)
print(ar)
print(ar[1])

[1 2 3 4 5 6 7 8]
4
8
1


[10 20 30 40 50]
50
10


[11 22 33 44 55]
33
55


[10 20]
20


[1 2 3 4 5]
2


In [75]:
# access 2- d array
arr = ([[1,2,3,4,5,6,7]])
a = np.array(arr)
print(a)
print(a[0])
print(a[-1])
print('\n')
l = [[10,20,30,40],[50,60,70,80]]
ar = np.array(l)
print(ar)
print(ar[0][1])
print(ar[1][2])
print(ar[0,3])
print(ar[1,1])
print('\n')
tup = ([[1,2,3,4],[5,6,7,8]])
ar = np.array(tup)
print(ar)
print(ar[1][0])
print(ar[0,3])
print('\n')
ar = np.array([[11,22,33],[44,55,66]])
print(ar)
print(ar[0][2])
print(ar[1,2])

[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


[[10 20 30 40]
 [50 60 70 80]]
20
70
40
60


[[1 2 3 4]
 [5 6 7 8]]
5
4


[[11 22 33]
 [44 55 66]]
33
66


In [99]:
# access 3 - d array 
a = [[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]
ar = np.array(a)
print(ar)
print(ar[0][1])
print(ar[0][0][2])
print(ar[1,1,0])
print(ar[1,0,3])
print('\n')
l = [[[1,2,3,4,5,6]]]
ar = np.array(l)
print(ar)
print(ar[0])
print(ar[-1])
print('\n')
tup = ([[[1,2,3],[4,5,6]]])
ar = np.array(tup)
print(ar[0][1])
print(ar[0][0])
print(ar[0,0,1])
print(ar[0,1,2])
arr = ([[[10,20,30]]])
ar = np.array(arr)
print(ar)
print(ar[0][0])
print(ar[0,0,1])
s = [[[1,2,3,4,5]]]
arr = np.array(s)
print(arr)
print(arr[0][0][1])
print(arr[0][0][2])
print(arr[0,0,4])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[5 6 7 8]
3
13
12


[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


[4 5 6]
[1 2 3]
2
6
[[[10 20 30]]]
[10 20 30]
20
[[[1 2 3 4 5]]]
2
3
5


In [103]:
a = np.array(10)
b = np.array([1,2,3,4])
c = np.array([[10,20,30,40]])
d = np.array([[[11,22,33]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [105]:
a = np.array(10)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[11,22,33],[44,55,66]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [106]:
arr = np.array([10], ndmin = 2)
print(arr)

[[10]]


In [107]:
arr = np.array([20,30,40], ndmin = 3)
print(arr)

[[[20 30 40]]]


In [108]:
arr = np.array([11,22,33,44], ndmin = 4)
print(arr)

[[[[11 22 33 44]]]]


In [109]:
a = np.array([11,12,13,14], ndmin = 5)
print(a)

[[[[[11 12 13 14]]]]]


In [110]:
b = np.array([100,200,300], ndmin = 6)
print(b)

[[[[[[100 200 300]]]]]]


In [140]:
# slicing 1 -d array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr[0:])
print(arr[3:])
print(arr[3:6])
print(arr[5:7])
print(arr[-4:-1])
print(arr[-3:-1])
print(arr[0:9:2])
l = [10,20,30,40,50,60]
ar = np.array(l)
print(ar)
print(ar[1:5])
print(ar[0:4])
print(ar[-4:])
print(ar[0:6:2])
tup = (11,22,33,44,55,66)
ar = np.array(tup)
print(ar[0:1])
print(ar[2:4])
print(ar[-1])
print(ar[0:6:3])
a = ([1,2,3,4,5,6,7,8,9])
ar = np.array(a)
print(ar)
print(ar[0:5])
print(ar[1:4])
print(ar[6:10])
print(ar[0:9:4])
b = [11,12,13,14,15,16]
arr = np.array(b)
print(b)
print(b[2:5])
print(b[1:4])
print(b[-5:-2])
print(b[0:6:2])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6]
[6 7]
[6 7 8]
[7 8]
[1 3 5 7 9]
[10 20 30 40 50 60]
[20 30 40 50]
[10 20 30 40]
[30 40 50 60]
[10 30 50]
[11]
[33 44]
66
[11 44]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[2 3 4]
[7 8 9]
[1 5 9]
[11, 12, 13, 14, 15, 16]
[13, 14, 15]
[12, 13, 14]
[12, 13, 14]
[11, 13, 15]


In [163]:
# slicing 2 - d array
arr = np.array([[1,2,3,4,5,6,7,8,9]])
print(arr)
print(arr[0:3])
print(arr[0,3:10])
print(arr[0,0:4])
print(arr[0,1:7])
print('\n')
l = np.array([[11,22,33],[44,55,66]])
print(l)
print(l[0,0:3])
print(l[0:2,0:2])
print(l[0:2,2:])
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(arr[0])
print(arr[0:2,0:1])
print(arr[0:2,1:3])
tup =([[1,2,3,4,5,6,7,8,9,10]])
arr = np.array(tup)
print(arr)
print(arr[0,0:4])
print(arr[0,0:2])
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[0:3,1:3])
print(a[0:3,3:])

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[4 5 6 7 8 9]
[1 2 3 4]
[2 3 4 5 6 7]


[[11 22 33]
 [44 55 66]]
[11 22 33]
[[11 22]
 [44 55]]
[[33]
 [66]]
[[10 20 30 40]
 [50 60 70 80]]
[10 20 30 40]
[[10]
 [50]]
[[20 30]
 [60 70]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[1 2 3 4]
[1 2]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4]
 [ 8]
 [12]]


In [186]:
 # slicing  3 - d array
arr = ([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a = np.array(arr)
print(a)
print('\n')
print(a[:,1:3])
print(a[0,0:2])
print(a[0:2,1:4])
l = [[[1,2,3,4,5,6,7,8,9]]]
ar = np.array(l)
print(ar[0,0:1])
print(ar[0,0:])
print('\n')
s = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar = np.array(s)
print(ar)
print(ar[0,1:2])
print(ar[0,1:0])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


[[[ 5  6  7  8]]

 [[13 14 15 16]]]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 5  6  7  8]]

 [[13 14 15 16]]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[4 5 6]]
[]


In [9]:
import numpy as np
arr =([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
ar = np.array(arr)
print(ar)
print('\n')
print(ar[:,:,2:])
print('\n')
print(ar[:,:,0:2])
print(ar[0:1,0:2,2:3])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]

 [[19 20]
  [23 24]]]


[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 14]]

 [[17 18]
  [21 22]]]
[[[3]
  [7]]]


In [30]:
arr = ([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar = np.array(arr)
print(ar)
print('\n')
print(ar[:1,1:2,0:2])
print(ar[:2,1:2,1:2])
print(ar[:2,0:1,0:1])
print(ar[:3,0:3,0:1])
print(ar[0:1,0:1,0:1])
print(ar[0][0])
print(ar[0,0,1])
print(ar[:,:,0:2])
print()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[4 5]]]
[[[ 5]]

 [[11]]]
[[[1]]

 [[7]]]
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]
[[[1]]]
[1 2 3]
2
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [31]:
# date types 
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [32]:
arr = np.array([[10,20,30,40,50]])
print(arr)
print(arr.dtype)

[[10 20 30 40 50]]
int32


In [33]:
arr = np.array([[10.2,10.3,10.4,10.5]])
print(arr)
print(arr.dtype)

[[10.2 10.3 10.4 10.5]]
float64


In [34]:
arr = np.array([10+3j,2+5j])
print(arr)
print(arr.dtype)

[10.+3.j  2.+5.j]
complex128


In [35]:
arr = np.array([True, False])
print(arr)
print(arr.dtype)

[ True False]
bool


In [36]:
arr = np.array(['aa','bb','cc','dd','ee'])
print(arr)
print(arr.dtype)

['aa' 'bb' 'cc' 'dd' 'ee']
<U2


In [37]:
arr = np.array([2-11-2023])
print(arr)
print(arr.dtype)

[-2032]
int32


In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
int32


In [40]:
# creating array with defined date type
arr = np.array([1,2,3,4,5], dtype = 'int')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [41]:
arr = np.array([11,22,333,44], dtype = 'float')
print(arr)
print(arr.dtype)

[ 11.  22. 333.  44.]
float64


In [42]:
arr = np.array(['1','2','3','4','5'], dtype = 'bool')
print(arr)
print(arr.dtype)

[ True  True  True  True  True]
bool


In [43]:
arr = np.array([10,20,30,40,50], dtype = 'i')
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int32


In [46]:
arr = np.array([1.1,1.2,1.3,1.4,1.5], dtype = 'int')
print(arr)
print(arr.dtype)

[1 1 1 1 1]
int32


In [47]:
arr = np.array([1,2,3,4,5,6,7], dtype = 'i2')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
int16


In [48]:
arr = np.array([10,20,30,40,50], dtype = 'i4')
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int32


In [49]:
arr = np.array([11,22,33,44,55],dtype = 'i8')
print(arr)
print(arr.dtype)

[11 22 33 44 55]
int64


In [51]:
arr = np.array([10.1,20.1,30.1,40.1],dtype = 'float')
print(arr)
print(arr.dtype)

[10.1 20.1 30.1 40.1]
float64


In [69]:
# date type conversion
arr = np.array([1,2,3,4,6,7])
ar = arr.astype('float')
print(ar)
print(ar.dtype)
a = np.array([1.1,2.1,3.1,4.1,5.1])
b = a.astype('int')
print(b)
print(b.dtype)
b = np.array([0,1,2,-1])
c = b.astype('bool')
print(c)
c = np.array(['11','22','33','44','55'])
d = c.astype('float')
print(d)
d = np.array([10,20,30,40,50,60])
e = d.astype('str')
print(e)
arr = np.array([True , False, True])
ar = arr.astype('int')
print(ar)
arr = np.array([1+2j,2+3j,3+4j,4+5j])
ar = arr.astype('bool')
print(ar)
arr = np.array([True , False])
ar = arr.astype('complex')
print(ar)
ar = np.array([[1,2,3,4,5,6,7]])
a = ar.astype('float')
print(a)

[1. 2. 3. 4. 6. 7.]
float64
[1 2 3 4 5]
int32
[False  True  True  True]
[11. 22. 33. 44. 55.]
['10' '20' '30' '40' '50' '60']
[1 0 1]
[ True  True  True  True]
[1.+0.j 0.+0.j]
[[1. 2. 3. 4. 5. 6. 7.]]


In [77]:
# copy
ar = np.array([1,2,3,4,5,6,7])
arr = ar.copy()
arr[0] = 100
print(ar)
print(arr)
arr = np.array([[10,20,30,40,50]])
a = arr.copy()
a[0][1] = 400
print(arr)
print(a)
arr = np.array([[10.1,20.1,30.1,40.1]])
a = arr.copy()
a[0][3] = 30
print(arr)
print(a)
ar = np.array([11,22,33,44,55,66])
a = ar.copy()
a[5] = 60
print(a)
print(ar)
a = np.array([[[1,2,3,4,5,6,7,8]]])
b = a.copy()
b[0][0][5] = 60
print(a)
print(b)

[1 2 3 4 5 6 7]
[100   2   3   4   5   6   7]
[[10 20 30 40 50]]
[[ 10 400  30  40  50]]
[[10.1 20.1 30.1 40.1]]
[[10.1 20.1 30.1 30. ]]
[11 22 33 44 55 60]
[11 22 33 44 55 66]
[[[1 2 3 4 5 6 7 8]]]
[[[ 1  2  3  4  5 60  7  8]]]


In [85]:
# view 
arr = np.array([1,2,3,4,5,6])
ar = arr.view()
ar[3]=40
print(arr)
print(ar)
a = np.array([[10,20,30,40,50]])
b = a.view()
b[0][3] = 4
print(a)
print(b)
b = np.array([[[1.1,2.1,3.1,4.1,5.1]]])
c = b.view()
c[0][0][4] = 50
print(b)
print(c)
x = np.array([1,2,3,4,5,6,7])
y = x.view()
y[1] = 10
print(x)
print(y)
y = np.array([[100,200,300]])
z = y.view()
z[0][1] = 1
print(y)
print(z)

[ 1  2  3 40  5  6]
[ 1  2  3 40  5  6]
[[10 20 30  4 50]]
[[10 20 30  4 50]]
[[[ 1.1  2.1  3.1  4.1 50. ]]]
[[[ 1.1  2.1  3.1  4.1 50. ]]]
[ 1 10  3  4  5  6  7]
[ 1 10  3  4  5  6  7]
[[100   1 300]]
[[100   1 300]]


In [96]:
# base
ar = np.array([1,2,3,4,5])
a = ar.copy()
b = ar.view()
print(a.base)
print(b.base)
arr = np.array([[10,20,30,40]])
a = arr.copy()
b = arr.view()
print(a.base)
print(b.base)
ar = np.array([[[11,22,33,44,55]]])
a = ar.copy()
b = ar.view()
print(a.base)
print(b.base)
a = np.array([[1.1,2.2,3.3,4.4]])
b = a.copy()
c = a.view()
c[0][2] = 20
print(b.base)
print(c.base)
a = np.array([[[1,2,3,4,5,6,7]]])
b = a.copy()
c = a.view()
c[0][0][1] = 20
print(b.base)
print(c.base)
     
     
     

None
[1 2 3 4 5]
None
[[10 20 30 40]]
None
[[[11 22 33 44 55]]]
None
[[ 1.1  2.2 20.   4.4]]
None
[[[ 1 20  3  4  5  6  7]]]


In [144]:
# array reshaping
# 1 - d array
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.size)
print(arr.shape)
x = arr.reshape(9)
y = arr.reshape(9,1)
z = arr.reshape(3,3,1)
print(x)
print(y)
print(z)
arr = np.array([10,20,30,40,50,60])
print(arr)
print(arr.size)
print(arr.shape)
a = arr.reshape(6)
b = arr.reshape(3,2)
c = arr.reshape(2,3,1)
print(a)
print(b)
print(c)
arr = np.array([11,22,33,44,55,66])
print(arr)
x = arr.reshape(6)
y = arr.reshape(1,6)
z = arr.reshape(1,6,1)
print(x)
print(y)
print(z)
ar = np.array([1,12,13,14,15,16])
print(ar)
a = ar.reshape(6)
print(a)
b = ar.reshape(6,1)
print(b)
c = ar.reshape(1,6,1)
print(c)


[1 2 3 4 5 6 7 8 9]
9
(9,)
[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
[10 20 30 40 50 60]
6
(6,)
[10 20 30 40 50 60]
[[10 20]
 [30 40]
 [50 60]]
[[[10]
  [20]
  [30]]

 [[40]
  [50]
  [60]]]
[11 22 33 44 55 66]
[11 22 33 44 55 66]
[[11 22 33 44 55 66]]
[[[11]
  [22]
  [33]
  [44]
  [55]
  [66]]]
[ 1 12 13 14 15 16]
[ 1 12 13 14 15 16]
[[ 1]
 [12]
 [13]
 [14]
 [15]
 [16]]
[[[ 1]
  [12]
  [13]
  [14]
  [15]
  [16]]]


In [146]:
# 2 - d array
ar = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14]])
print(ar)
print(ar.size)
print(ar.shape)
a = ar.reshape(14)
print(a)
b = ar.reshape(14,1)
print(b)
c = ar.reshape(7,2,1)
print(c)
arr = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
print(arr)
print(arr.shape)
print(arr.size)
a = arr.reshape(-1)
print(a)
b = arr.reshape(12)
print(b)
c = arr.reshape(4,3,1)
print(c)
arr = np.array([[1,2,3,4,5,6]])
print(arr)
a =arr.reshape(6)
b = arr.reshape(6,1)
c = arr.reshape(3,2,1)
print(a)
print(b)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
14
(1, 14)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
(1, 12)
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [133]:
# 3 - d array
arr = ([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]]])
ar = np.array(arr)
print(ar)
a = ar.reshape(16)
print(a)
b = ar.reshape(16,1)
print(b)
c = ar.reshape(4,4,1)
print(c)
ar = np.array([[[1,2,3,4,5,6,7,8]]])
print(ar)
a = ar.reshape(8)
print(a)
b = ar.reshape(4,2)
print(b)
c = ar.reshape(2,4,1)
print(c)
a = np.array([[[1,2,3,4]]])
print(a)
x = a.reshape(4)
y = a.reshape(2,2)
z = a.reshape(2,2,1)
print(x)
print(y)
print(z)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]]
[[[1 2 3 4 5 6 7 8]]]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]
[[[1 2 3 4]]]
[1 2 3 4]
[[1 2]
 [3 4]]
[[[1]
  [2]]

 [[3]
  [4]]]


In [139]:
# unknown dimension
ar = np.array([1,2,3,4,5,6])
print(ar)
x = ar.reshape(-1)
print(x)
arr = np.array([[1,2,3,4,5,6,7,8]])
print(arr)
x = arr.reshape(8,-1,)
print(x)
y = arr.reshape(4,2,-1)
print(y)
a = np.array([[[1,2,3,4,5,6,7]]])
print(a)
x = a.reshape(7)
print(x)
y = a.reshape(7,-1)
print(y)
z = a.reshape(7,1,-1)
print(z)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
[[[1 2 3 4 5 6 7]]]
[1 2 3 4 5 6 7]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]]


In [143]:
# flattening an array
arr = np.array([1,2,3,4,5])
print(arr)
a = arr.reshape(-1)
print(a)
b = arr.reshape(-1,5)
print(b)
ar = np.array([[1,2,3,4,5,6]])
print(ar)
a = ar.reshape(-1)
print(a)
arr = np.array([[[1,2,3,4,5,6,7,8]]])
print(arr)
a = arr.reshape(-1)
print(a)

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3 4 5]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[[[1 2 3 4 5 6 7 8]]]
[1 2 3 4 5 6 7 8]


In [153]:
# numpy array iterating
arr = np.array([1,2,3,4,5,6,7])
print(arr)
for i in arr:
    print(i)
    
ar = np.array([10,20,30,40,50])
print(ar)
for x in ar:
    print(x)
arr = np.array([1.1,2.2,3.3,4.4,5.5])
print(a)
for i in arr:
    print(i)
ar = np.array([100,200,300,400])
print(ar)
for x in ar:
    print(x)
arr = np.array(['1','2','3','4','5'])
print(arr)
for x in arr:
    print(x)

[1 2 3 4 5 6 7]
1
2
3
4
5
6
7
[10 20 30 40 50]
10
20
30
40
50
[1.1 2.2 3.3 4.4 5.5]
1.1
2.2
3.3
4.4
5.5
[100 200 300 400]
100
200
300
400
['1' '2' '3' '4' '5']
1
2
3
4
5


In [160]:
# iterating 2 - d array
arr = np.array([[1,2,3,4,5,6,7]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)
ar = np.array([[1.1,2.2,3.3,4.4,5.5]])
print(ar)
for x in  ar:
    print(x)
    for y in x:
        print(y)
a = np.array([[10,20,30,40,50,60]])
print(a)
for i in a:
    print(i)
    for x in i:
        print(x)
b = np.array([[11,22,33,44,55,66]])
print(b)
for i in b:
    print(i)
    for x in i:
        print(x)
c = np.array([['11','22','33','44','55']])
print(c)
for x in c:
    print(x)
    for y in x:
        print(y)

[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
1
2
3
4
5
6
7
[[1.1 2.2 3.3 4.4 5.5]]
[1.1 2.2 3.3 4.4 5.5]
1.1
2.2
3.3
4.4
5.5
[[10 20 30 40 50 60]]
[10 20 30 40 50 60]
10
20
30
40
50
60
[[11 22 33 44 55 66]]
[11 22 33 44 55 66]
11
22
33
44
55
66
[['11' '22' '33' '44' '55']]
['11' '22' '33' '44' '55']
11
22
33
44
55


In [175]:
# iterating 3 - d array
arr = np.array([[[1,2,3,4,5,6,7,8]]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)
            
ar = np.array([[[11,22,33,44,55]]])
print(ar)
for x in ar:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)
a =np.array([[['1','2','3','4','5']]])
print(a)
for x in a:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)
b = np.array([[[10,20,30,40,50]]])
print(b)
for x in b:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)
c = np.array([[[11,12,13,14,15,16]]])
print(c)
for a in c:
    print(a)
    for b in a:
        print(b)
        for d in b:
            print(d)
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)
for x in d:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[[1 2 3 4 5 6 7 8]]]
[[1 2 3 4 5 6 7 8]]
[1 2 3 4 5 6 7 8]
1
2
3
4
5
6
7
8
[[[11 22 33 44 55]]]
[[11 22 33 44 55]]
[11 22 33 44 55]
11
22
33
44
55
[[['1' '2' '3' '4' '5']]]
[['1' '2' '3' '4' '5']]
['1' '2' '3' '4' '5']
1
2
3
4
5
[[[10 20 30 40 50]]]
[[10 20 30 40 50]]
[10 20 30 40 50]
10
20
30
40
50
[[[11 12 13 14 15 16]]]
[[11 12 13 14 15 16]]
[11 12 13 14 15 16]
11
12
13
14
15
16
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12


In [174]:
# iterating array using nditer()
arr = np.array([1,2,3,4,5,6,7])
print(arr)
for x in np.nditer(arr):
    print(x)
ar = np.array([[10,20,30,40,50]])
print(ar)
for x in np.nditer(ar):
    print(x)
a = np.array([[[11,22,33,44,55,66]]])
print(a)
for x in np.nditer(a):
    print(x)
b = np.array(['1','2','3','4','5'])
print(b)
for x in np.nditer(b):
    print(x)
c = np.array([[['10','20','30','40','50']]])
print(c)
for x in np.nditer(c):
    print(x)

[1 2 3 4 5 6 7]
1
2
3
4
5
6
7
[[10 20 30 40 50]]
10
20
30
40
50
[[[11 22 33 44 55 66]]]
11
22
33
44
55
66
['1' '2' '3' '4' '5']
1
2
3
4
5
[[['10' '20' '30' '40' '50']]]
10
20
30
40
50


In [181]:
# casting array element from one type to another type
arr = np.array([1,2,3,4,5,6])
print(arr)
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(x)
ar = np.array([[1,2,3],[4,5,6]])
print(ar)
for x in np.nditer(ar, flags = ['buffered'], op_dtypes = ['U']):
    print(x)
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a)
for x in np.nditer(a, flags = ['buffered'], op_dtypes = ['float']):
    print(x)
b = np.array([[['10','20','30','40','50']]])
print(b)
for b in np.nditer(b, flags = ['buffered'], op_dtypes = ['U']):
    print(b)
c = np.array([[10,20,30],[40,50,60]])
print(c)
for x in np.nditer(c, flags = ['buffered'], op_dtypes = ['float']):
    print(x)

[1 2 3 4 5 6]
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
[[['10' '20' '30' '40' '50']]]
10
20
30
40
50
[[10 20 30]
 [40 50 60]]
10.0
20.0
30.0
40.0
50.0
60.0


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
l = [1,2,3,4,5,6,7,8]
ar = np.array(l)
print(ar)
print(type(ar))
tup = (11,22,33,44,55)
ar = np.array(tup)
print(ar)
print(type(ar))
ar = np.array(100)
print(ar)
print(ar.ndim)
tup = (1,2,3,4,5,6)
ar = np.array(tup)
print(ar)
print(ar.ndim)
l = [[10,20,30,40,50]]
ar = np.array(l)
print(ar)
print(ar.ndim)
tup = ([[[10,20,30,40,50],[60,70,80,90,100]]])
ar = np.array(tup)
print(ar)
print(ar.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[11 22 33 44 55]
<class 'numpy.ndarray'>
100
0
[1 2 3 4 5 6]
1
[[10 20 30 40 50]]
2
[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]]
3


In [29]:
# accessing array
arr = ([1,2,3,4,5,6,7,8,9])
ar = np.array(arr)
print(ar)
print(ar.ndim)
print(ar[0])
print(ar[-1])
print(ar[3])
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
print(ar.ndim)
print(ar[0][0])
print(ar[0][2])
print(ar[0,1])
ar = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print(ar)
print(ar.ndim)
print(ar[0][0][1])
print(ar[0][1][-1])
print(ar[0,0,0:3])
print(ar[0,1,1:4])

[1 2 3 4 5 6 7 8 9]
1
1
9
4
[[1 2 3 4]
 [5 6 7 8]]
2
1
3
2
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
3
2
10
[1 2 3]
[7 8 9]


In [30]:
a = np.array(10)
b = np.array([1,2,3,4,5])
c = np.array([[10,20,30,40,50]])
d = np.array([[[100,200,300,400]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [31]:
arr = np.array([10,20,30,40], ndmin = 4)
print(arr)

[[[[10 20 30 40]]]]


In [59]:
# slicing array
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)
print(ar[0:3])
print(ar[1:4])
print(ar[7:])
print(ar[1:-1])
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr[0,0:2])
print(arr[1,1:2])
print(arr[0:,2:])
arr = np.array([[[11,22,33,44],[55,66,77,88]],[[99,100,110,120],[130,140,150,160]]])
print(arr)
print(arr[:1,0:2,2:3])
print(arr[1:2,0:2,2:3])
print(arr[:,:,3:])
print(arr[:,:,0:2,])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[2 3 4]
[8 9]
[2 3 4 5 6 7 8]
[[10 20 30]
 [40 50 60]]
[10 20]
[50]
[[30]
 [60]]
[[[ 11  22  33  44]
  [ 55  66  77  88]]

 [[ 99 100 110 120]
  [130 140 150 160]]]
[[[33]
  [77]]]
[[[110]
  [150]]]
[[[ 44]
  [ 88]]

 [[120]
  [160]]]
[[[ 11  22]
  [ 55  66]]

 [[ 99 100]
  [130 140]]]


In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr[0:3:2])
print(arr[1:5:5])

[ 1  2  3  4  5  6  7  8  9 10]
[1 3]
[2]


In [68]:
arr = np.array([[1,2,3,4,5,6,7,8,9,0]])
print(arr)
print(arr[0:3,1])
print(arr[:,2])
print(arr[0,0:5:2])
print(arr[0,1:7:4])

[[1 2 3 4 5 6 7 8 9 0]]
[2]
[3]
[1 3 5]
[2 6]


In [71]:
arr = np.array([[[10,20,30,40,50,60,70]]])
print(arr)
print(arr[0,0:3,2])
print(arr[0,0:2,1:5:2])
print(arr[0,0:1,0:8:2])

[[[10 20 30 40 50 60 70]]]
[30]
[[20 40]]
[[10 30 50 70]]


In [76]:
# date type array
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)
print(ar.dtype)
ar = np.array([1.1,2.2,3.3,4.4,5.5])
print(ar)
print(ar.dtype)
ar = np.array(['11','22','33','44','55'])
print(ar)
print(ar.dtype)
ar = np.array([True , False])
print(ar)
print(ar.dtype)
ar = np.array([0+1j,2+3j,4+5j])
print(ar)
print(ar.dtype)

[1 2 3 4 5 6 7 8 9]
int32
[1.1 2.2 3.3 4.4 5.5]
float64
['11' '22' '33' '44' '55']
<U2
[ True False]
bool
[0.+1.j 2.+3.j 4.+5.j]
complex128


In [87]:
arr = np.array([10,20,30,40], dtype = 'int')
print(arr)
print(arr.dtype)
arr = np.array([10.2,10.3,10.4,10.5], dtype = 'float')
print(arr)
print(arr.dtype)
arr = np.array([True, False], dtype = 'bool')
print(arr)
print(arr.dtype)
arr = np.array([10+2j,3+4j,5+6j], dtype = 'complex')
print(arr)
print(arr.dtype)
arr = np.array([10,20,30,40], dtype = 'float')
print(arr)
arr = np.array([1,2,3,4,5,6,7], dtype = 'i2')
print(arr)
print(arr.dtype)
arr = np.array([10,20,30,40,50],dtype = 'i4')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55,66], dtype = 'i8')
print(arr)
print(arr.dtype)

[10 20 30 40]
int32
[10.2 10.3 10.4 10.5]
float64
[ True False]
bool
[10.+2.j  3.+4.j  5.+6.j]
complex128
[10. 20. 30. 40.]
[1 2 3 4 5 6 7]
int16
[10 20 30 40 50]
int32
[11 22 33 44 55 66]
int64


In [92]:
# date type conversion
arr = np.array([10,20,30,40,50,60])
a = arr.astype('float')
print(arr)
print(a)
arr = np.array([1.1,2.2,3.3,4.4,5.5])
a = arr.astype('int')
print(arr)
print(a)
a = np.array([True, False, True])
b = a.astype('int')
print(a)
print(b)
a = np.array([1+2j,3+4j,5+6j])
b = a.astype('bool')
print(a)
print(b)
a = np.array(['11','22','33','44','55'])
b = a.astype('float')
print(a)
print(b)

[10 20 30 40 50 60]
[10. 20. 30. 40. 50. 60.]
[1.1 2.2 3.3 4.4 5.5]
[1 2 3 4 5]
[ True False  True]
[1 0 1]
[1.+2.j 3.+4.j 5.+6.j]
[ True  True  True]
['11' '22' '33' '44' '55']
[11. 22. 33. 44. 55.]


In [96]:
# copy
a = np.array([10,20,30,40,50])
b = a.copy()
b[0] = 100
print(a)
print(b)
a = np.array([[11,22,33,44,55]])
b = a.copy()
b[0,0] = 20
print(a)
print(b)
a = np.array([[[100,200,300,400,500]]])
b = a.copy()
b[0,0,3] = 4
print(a)
print(b)

[10 20 30 40 50]
[100  20  30  40  50]
[[11 22 33 44 55]]
[[20 22 33 44 55]]
[[[100 200 300 400 500]]]
[[[100 200 300   4 500]]]


In [99]:
# view
a = np.array([10,20,30,40,50])
b = a.view()
b[4] = 5
print(a)
print(b)
arr = np.array([[11,22,33,44,55]])
a = arr.view()
a[0,3] = 400
print(arr)
print(a)
ar = np.array([[[1,2,3,4,5,6,7,8]]])
a = ar.view()
a[0,0,-1] = 800
print(ar)
print(a)

[10 20 30 40  5]
[10 20 30 40  5]
[[ 11  22  33 400  55]]
[[ 11  22  33 400  55]]
[[[  1   2   3   4   5   6   7 800]]]
[[[  1   2   3   4   5   6   7 800]]]


In [102]:
# base
a = np.array([11,12,13,14,15])
b = a.copy()
c = a.view()
print(b.base)
print(c.base)
arr = np.array([[10,20,30,40,50,60]])
a = arr.copy()
b = arr.view()
print(a.base)
print(b.base)
ar = np.array([[[11,22,33,44,55,66]]])
a = ar.copy()
b = ar.view()
b[0,0,2]= 30
print(a.base)
print(b.base)

None
[11 12 13 14 15]
None
[[10 20 30 40 50 60]]
None
[[[11 22 30 44 55 66]]]


In [111]:
# array reshaping
ar = np.array([11,22,33,44,55,66])
a = ar.reshape(1,6)
print(a)
b = ar.reshape(6,1,1)
print(b)
c = ar.reshape(6)
print(c)
arr = np.array([[1,2,3,4,5,6,7,8,9]])
a =arr.reshape(9)
print(a)
b = arr.reshape(3,3,1)
print(b)
c = arr.reshape(9,1)
print(c)
arr = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14]]])
print(arr)
a = arr.reshape(14)
print(a)
b = arr.reshape(7,2)
print(b)
c = arr.reshape(7,2,1)
print(c)

[[11 22 33 44 55 66]]
[[[11]]

 [[22]]

 [[33]]

 [[44]]

 [[55]]

 [[66]]]
[11 22 33 44 55 66]
[1 2 3 4 5 6 7 8 9]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]]


In [116]:
# unknown dimension
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
x = a.reshape(9,-1)
print(x)
y = a.reshape(9,1,-1)
print(y)
a = np.array([[10,20,30,40,50]])
print(a)
x = a.reshape(5,-1)
print(x)
y = a.reshape(5,1,-1)
print(y)
a = np.array([[[1,2,3,4,5,6,7,8,9]]])
print(a)
x = a.reshape(9,-1)
print(x)
y = a.reshape(9,1,-1)
print(y)

[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]

 [[9]]]
[[10 20 30 40 50]]
[[10]
 [20]
 [30]
 [40]
 [50]]
[[[10]]

 [[20]]

 [[30]]

 [[40]]

 [[50]]]
[[[1 2 3 4 5 6 7 8 9]]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]

 [[9]]]


In [120]:
# flattening array
a = np.array([10,20,30,40,50])
print(a)
x = a.reshape(-1)
print(x)
b = np.array([[11,22,33,44,55,66]])
print(b)
y = b.reshape(-1)
print(y)
c = np.array([[[100,200,300,400,500]]])
z = c.reshape(-1)
print(z)

[10 20 30 40 50]
[10 20 30 40 50]
[[11 22 33 44 55 66]]
[11 22 33 44 55 66]
[100 200 300 400 500]


In [123]:
# numpy array iterating
ar = np.array([1,2,3,4,5,6])
print(ar)
for x in ar:
    print(x)
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
for x in arr:
    print(x)
    for y in x:
        print(y)
ar = np.array([[[11,22,33,44,55,66,77]]])
print(ar)
for x in ar:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[1 2 3 4 5 6]
1
2
3
4
5
6
[[10 20 30]
 [40 50 60]]
[10 20 30]
10
20
30
[40 50 60]
40
50
60
[[[11 22 33 44 55 66 77]]]
[[11 22 33 44 55 66 77]]
[11 22 33 44 55 66 77]
11
22
33
44
55
66
77


In [129]:
# numpy array using nditer()
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
for x in np.nditer(a):
    print(x)
b =np.array ([[10,20,30],[40,50,60]])
print(b)
for x in np.nditer(b):
    print(x)
c = np.array([[[11,22,33,44],[55,66,77,88]],[[99,100,110,120],[130,140,150,160]]])
print(c)
for x in np.nditer(c):
    print(x)

[1 2 3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9
[[10 20 30]
 [40 50 60]]
10
20
30
40
50
60
[[[ 11  22  33  44]
  [ 55  66  77  88]]

 [[ 99 100 110 120]
  [130 140 150 160]]]
11
22
33
44
55
66
77
88
99
100
110
120
130
140
150
160


In [138]:
# casting element one type to another type
a = np.array([10,20,30,40,50])
print(a)
for x in np.nditer(a, flags = ['buffered'], op_dtypes = ['S']):
    print(x)
b = np.array([[11,22,33,44,55],[66,77,88,99,100]])
print(b)
for i in np.nditer(b, flags = ['buffered'], op_dtypes = ['float']):
    print(i)
c = np.array([[[10.1,20.1,30.1,40.1,50.1]]])
print(c)
for i in np.nditer(c, flags = ['buffered'], op_dtypes = ['U']):
    print(i)
d = np.array([[['1','2','3'],['4','5','6']],[['7','8','9'],['10','11','12']]])
print(d)
for x in np.nditer(d, flags = ['buffered'], op_dtypes = ['U']):
    print(x)

[10 20 30 40 50]
b'10'
b'20'
b'30'
b'40'
b'50'
[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
11.0
22.0
33.0
44.0
55.0
66.0
77.0
88.0
99.0
100.0
[[[10.1 20.1 30.1 40.1 50.1]]]
10.1
20.1
30.1
40.1
50.1
[[['1' '2' '3']
  ['4' '5' '6']]

 [['7' '8' '9']
  ['10' '11' '12']]]
1
2
3
4
5
6
7
8
9
10
11
12


In [142]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
l = [10,20,30,40,50]
ar = np.array(l)
print(ar)
print(type(ar))
tup = (11,22,33,44,55,66)
ar = np.array(tup)
print(ar)
print(type(ar))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>
[11 22 33 44 55 66]
<class 'numpy.ndarray'>


In [147]:
arr = np.array(100)
print(arr)
print(arr.ndim)
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
ar = np.array([[11,22,33,44,55]])
print(ar)
print(ar.ndim)
ar = np.array([[[11,12,13,14,15,16]]])
print(ar)
print(ar.ndim)

100
0
[10 20 30 40 50]
1
[[11 22 33 44 55]]
2
[[[11 12 13 14 15 16]]]
3


In [157]:
# access 1 - d array
arr = np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[-1])
# 2 - d array
arr = np.array([[11,22,33,44,55,66,77]])
print(arr)
print(arr[0][0])
print(arr[0][-1])
print(arr[0,3])
print(arr[0,4])
# 3 - d array
arr = np.array([[[1,2,3,4,5,6,7,8]]])
print(arr)
print(arr[0][0][2])
print(arr[0][0][-1])
print(arr[0,0,-1])
print(arr[0,0,4])

[10 20 30 40 50]
10
50
[[11 22 33 44 55 66 77]]
11
77
44
55
[[[1 2 3 4 5 6 7 8]]]
3
8
8
5


In [158]:
a = np.array(10)
b = np.array([10,20,30,40,50])
c = np.array([[11,22,33,44]])
d = np.array([[[11,12,13,14]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [160]:
arr = np.array([[10,20,30,40]], ndmin = 4)
print(arr)

[[[[10 20 30 40]]]]


In [179]:
# array slicing
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a[0:3])
print(a[0:8:3])
print(a[0:-1:2])
print(a[3:])
print(a[:5])
arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(arr[0:,1:2])
print(arr[1:,2:])
print(arr[0:,2:])
arr = np.array([[[11,22,33],[44,55,66]]])
print(arr)
print(arr[0:,0:,0:1])
print(arr[0:,0:,2:])


[1 2 3 4 5 6 7 8]
[1 2 3]
[1 4 7]
[1 3 5 7]
[4 5 6 7 8]
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]
[[20]
 [50]]
[[60]]
[[30]
 [60]]
[[[11 22 33]
  [44 55 66]]]
[[[11]
  [44]]]
[[[33]
  [66]]]


In [182]:
# step value
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a[0:4:1])
print(a[1:7:2])
a = np.array([[1,2,3,4,5,6,7,8,9]])
print(a)
print(a[0,0:9:2])
print(a[0,0:5:1])
a = np.array([[10,20,30,40,50,60]])
print(a)
print(a[0,0:4:2])
print(a[0,1:6:2])

[1 2 3 4 5 6 7 8]
[1 2 3 4]
[2 4 6]
[[1 2 3 4 5 6 7 8 9]]
[1 3 5 7 9]
[1 2 3 4 5]
[[10 20 30 40 50 60]]
[10 30]
[20 40 60]


In [188]:
# data type
a = np.array([10,20,30,40])
print(a)
print(a.dtype)
b = np.array([1.1,2.2,3.3,4.4])
print(b)
print(b.dtype)
c= np.array(['1','2','3','4','5','6'])
print(c)
print(c.dtype)
d = np.array(['apple','kiwi'])
print(d)
print(d.dtype)
e = np.array([True, False])
print(e)
print(e.dtype)
f = np.array([1+2j,2+3j,4+5j])
print(f)
print(f.dtype)

[10 20 30 40]
int32
[1.1 2.2 3.3 4.4]
float64
['1' '2' '3' '4' '5' '6']
<U1
['apple' 'kiwi']
<U5
[ True False]
bool
[1.+2.j 2.+3.j 4.+5.j]
complex128


In [196]:
# array with a defined date type
arr = np.array([10,20,30,40,50,60],dtype = 'i')
print(arr)
print(arr.dtype)
arr = np.array([11,22,33,44,55,66],dtype = 'float')
print(arr)
print(arr.dtype)
arr = np.array([100,200,300,400,500],dtype = 'bool')
print(arr)
print(arr.dtype)
arr = np.array([1,2,3,4,5,6,7,8,9,10],dtype = 'complex')
print(arr)
print(arr.dtype)
arr = np.array([10,20,30,40,50,60],dtype = 'float')
print(arr)
print(arr.dtype)


[10 20 30 40 50 60]
int32
[11. 22. 33. 44. 55. 66.]
float64
[ True  True  True  True  True]
bool
[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
complex128
[10. 20. 30. 40. 50. 60.]
float64


In [203]:
# date type
a = np.array([1.1,2.1,3.1,4.1,5.1])
b = a.astype('int')
print(a)
print(b)
a = np.array([11,22,33,44,55,66])
b = a.astype('float')
print(b)
a = np.array([1,0,3,4])
b = a.astype('bool')
print(a)
print(b)
a = np.array([10,20,30,40,50])
b = a.astype('float')
print(a)
print(b)
a = np.array([1+0j,0+2j,1+3j])
b = a.astype('bool')
print(a)
print(b)
a = np.array([True , False, True])
b = a.astype('complex')
print(a)
print(b)


[1.1 2.1 3.1 4.1 5.1]
[1 2 3 4 5]
[11. 22. 33. 44. 55. 66.]
[1 0 3 4]
[ True False  True  True]
[10 20 30 40 50]
[10. 20. 30. 40. 50.]
[1.+0.j 0.+2.j 1.+3.j]
[ True  True  True]
[ True False  True]
[1.+0.j 0.+0.j 1.+0.j]


In [205]:
# copy
a = np.array([10,20,30,40,50,60])
b = a.copy()
b[3] = 200
print(a)
print(b)

[10 20 30 40 50 60]
[ 10  20  30 200  50  60]


In [208]:
# view
a = np.array([[1,2,3,4,5,6,7,8]])
b = a.view()
b[0][1] = 100
print(a)
print(b)

[[  1 100   3   4   5   6   7   8]]
[[  1 100   3   4   5   6   7   8]]


In [210]:
# base
a = np.array([[[10,20,30,40,50]]])
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

None
[[[10 20 30 40 50]]]


In [216]:
# array reshaping
a = np.array([1,2,3,4,5,6,7])
b = a.reshape(7,1)
print(b)
c = a.reshape(7,1,-1)
print(c)
b = np.array([[11,22,33,44,55]])
c = b.reshape(1,5,1)
print(c)
a = np.array([[1,2,3,4,5,6,7]])
b = a.reshape(-1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]]
[[[11]
  [22]
  [33]
  [44]
  [55]]]
[1 2 3 4 5 6 7]


In [220]:
arr = np.array([11,22,33,44,55,66])
print(arr)
for x in arr:
    print(x)
arr = np.array([[10,20,30,40]])
print(arr)
for i in arr:
    print(i)
    for j in i:
        print(j)
ar = np.array([[[1,2,3,4,5,6,7]]]) 
print(ar)
for i in ar:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)

[11 22 33 44 55 66]
11
22
33
44
55
66
[[10 20 30 40]]
[10 20 30 40]
10
20
30
40
[[[1 2 3 4 5 6 7]]]
[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
1
2
3
4
5
6
7


In [223]:
ar = np.array([[1,2,3,4,5,6,7,8]])
print(ar)
for i in np.nditer(ar):
    print(i)
    

[[1 2 3 4 5 6 7 8]]
1
2
3
4
5
6
7
8


In [225]:
ar = np.array([[[1,2,3,4,5,6]]])
print(ar)
for i in np.nditer(a, flags = ['buffered'],op_dtypes = ['S']):
    print(i)
for j in np.nditer(a, flags = ['buffered'], op_dtypes = ['U']):
    print(j)

[[[1 2 3 4 5 6]]]
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
1
2
3
4
5
6
7


In [5]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
l = [[10,20,30,40,50]]
arr = np.array(l)
print(arr)
print(type(arr))
tup = (11,22,33,44,55)
ar = np.array(tup)
print(ar)
print(type(ar))
print(ar.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[[10 20 30 40 50]]
<class 'numpy.ndarray'>
[11 22 33 44 55]
<class 'numpy.ndarray'>
1


In [9]:
arr = np.array(100)
print(arr)
print(arr.ndim)
arr = np.array([10,20,30,40])
print(arr)
print(arr.ndim)
arr = np.array([[11,22,33,44,55]])
print(arr)
print(arr.ndim)
arr = np.array([[[111,222,333,444,555]]])
print(arr)
print(arr.ndim)

100
0
[10 20 30 40]
1
[[11 22 33 44 55]]
2
[[[111 222 333 444 555]]]
3


In [11]:
a = np.array(100)
b = np.array([11,22,33,44,55])
c = np.array([[100,200,300,400]])
d = np.array([[[11,12,13,14,15]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr = np.array([[10,20,30,40,50]], ndmin = 5)
print(arr)

[[[[[10 20 30 40 50]]]]]


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr[0])
print(arr[4])
arr = np.array([[10,20,30,40,50]])
print(arr)
print(arr[0][0])
print(arr[0][-1])
arr = np.array([[[11,22,33,44,55,66,77,88]]])
print(arr)
print(arr[0][0][-1])
print(arr[0][0][5])

[ 1  2  3  4  5  6  7  8  9 10]
1
5
[[10 20 30 40 50]]
10
50
[[[11 22 33 44 55 66 77 88]]]
88
66


In [59]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr[0:3])
print(arr[1:8:2])
print(arr[1:9:7])
arr = np.array([[10,20,30,],[40,50,60]])
print(arr)
print(arr[0:,0:1])
print(arr[1:,0:3:2])
print(arr[0,0:3:2])
arr = np.array([[[11,22,33],[44,55,66]],[[77,88,99],[100,110,120]]])
print(arr)
print(arr[:,:,0:1])
print(arr[0,0,0:3:2])
print(arr[0:1,0:2,1:3:1])
print(arr[0:1,0:3,0:1:2])
print(arr[:,0:1,2:3])
print(arr[])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[2 4 6 8]
[2 9]
[[10 20 30]
 [40 50 60]]
[[10]
 [40]]
[[40 60]]
[10 30]
[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [100 110 120]]]
[[[ 11]
  [ 44]]

 [[ 77]
  [100]]]
[11 33]
[[[22 33]
  [55 66]]]
[[[11]
  [44]]]
[[[33]]

 [[99]]]


In [67]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
arr = np.array([1.1,2.2])
print(arr)
print(arr.dtype)
arr = np.array(['aa','bb','cc','dd'])
print(arr)
print(arr.dtype)
arr = np.array([1+2j,2+3j])
print(arr)
print(arr.dtype)
arr = np.array([True, False])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32
[1.1 2.2]
float64
['aa' 'bb' 'cc' 'dd']
<U2
[1.+2.j 2.+3.j]
complex128
[ True False]
bool


In [69]:
arr = np.array([1,2,3,4,5], dtype = 'float')
print(arr)
print(arr.dtype)
arr = np.array([['10','20','30']], dtype = 'int')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64
[[10 20 30]]
int32


In [70]:
arr = np.array([10,20,30,40])
print(arr)
a = arr.astype('float')
print(arr)
print(a)

[10 20 30 40]
[10 20 30 40]
[10. 20. 30. 40.]


In [75]:
arr = np.array([10,20,30,40,50])
print(arr)
a = arr.copy()
a[3]= 4
print(arr)
print(a)
arr = np.array([11,22,33,44,55])
print(arr)
a = arr.view()
a[1] = 2
print(arr)
print(a)
a = np.array([1,2,3,4,5,6])
print(a)
b = a.copy()
c = a.view()
print(b.base)
print(c.base)

[10 20 30 40 50]
[10 20 30 40 50]
[10 20 30  4 50]
[11 22 33 44 55]
[11  2 33 44 55]
[11  2 33 44 55]
[1 2 3 4 5 6]
None
[1 2 3 4 5 6]


In [77]:
arr = np.array([10,20,30,40,50])
print(arr)
a = arr.reshape(5,1)
print(a)
a = arr.reshape(5,1,-1)
print(a)

[10 20 30 40 50]
[[10]
 [20]
 [30]
 [40]
 [50]]
[[[10]]

 [[20]]

 [[30]]

 [[40]]

 [[50]]]


In [78]:
arr = np.array([[[10,20,30,40]]])
print(arr)
a = arr.reshape(-1)
print(a)

[[[10 20 30 40]]]
[10 20 30 40]


In [80]:
arr = np.array([1,2,3,4,5])
print(arr)
for i in arr:
    print(i)
arr = np.array([[11,22,33,44,55]])
print(arr)
for x in np.nditer(arr):
    print(x)

[1 2 3 4 5]
1
2
3
4
5
[[11 22 33 44 55]]
11
22
33
44
55


In [82]:
arr = np.array([[10,20,30,40,50,60]])
print(arr)
for i in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

[[10 20 30 40 50 60]]
b'10'
b'20'
b'30'
b'40'
b'50'
b'60'


In [113]:
arr = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(arr)
print('\n')
print(arr[0:1,0:1,0:3:2])
print(arr[0:1,0:2,0:3:2])
print(arr[0:2,0:3,0:2])
print(arr[0:1,0:3,0:2:2])
print(arr[1:2,1:,0:1])
print(arr[1:2,1:,0:])
print(arr[0:1,0:1,0:3])
print(arr[0:1,0:2,0:3])
print(arr[0:2,0:1,0:3])
print(arr[0:1,1:2,0:3])
print(arr[1:2,1:2,0:3])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


[[[10 30]]]
[[[10 30]
  [40 60]]]
[[[ 10  20]
  [ 40  50]]

 [[ 70  80]
  [100 110]]]
[[[10]
  [40]]]
[[[100]]]
[[[100 110 120]]]
[[[10 20 30]]]
[[[10 20 30]
  [40 50 60]]]
[[[10 20 30]]

 [[70 80 90]]]
[[[40 50 60]]]
[[[100 110 120]]]


In [136]:
a = np.array([11,22,33,44,55,66])
print(a)
print(a[0:2])
print(a[1:2])
print(a[0:1])
print(a[1:3])
print(a[0:2])
print(a[0:1])
print(a[1:3])
print(a[0:2])
print(a[1:2])
print(a[2:3])
print(a[0:3])
print(a[1:2])
print(a[0:2])
print(a[1:2])
print(a[0:1])
print(a[0:1])
print(a[0:1])
print(a[0:1])
print(a[1:2])
print(a[0:2])
print(a[0:1])

[11 22 33 44 55 66]
[11 22]
[22]
[11]
[22 33]
[11 22]
[11]
[22 33]
[11 22]
[22]
[33]
[11 22 33]
[22]
[11 22]
[22]
[11]
[11]
[11]
[11]
[22]
[11 22]
[11]
